# Generated by Django 3.1.7 on 2021-10-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.FloatField(max_length=16, null=True),
        ),
    ]
