# Generated by Django 3.1.7 on 2021-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211014_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
